sudo: required
services:
  - docker
before_install:
  - docker-compose up -d
  # Ensure LocalStack is up
  - docker-compose exec localstack timeout -t 60 bash -c "until curl --insecure --fail --silent https://localhost; do sleep 1; done"
  # Create the S3 Bucket (`files-test`) in LocalStack
  - docker-compose exec localstack curl --insecure -H "Host:files-test.s3.amazonaws.com" -H "Content-Length:0" -X PUT https://localhost
script:
  - FILES_URL=http://localhost:8080 script/test
notifications:
  email:
    - fertapric@gmail.com
