version: "3.0"

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      SERVICES: s3:443
      DEFAULT_REGION: us-east-1
      USE_SSL: "true"
    expose:
      - 443
    networks:
      files_network:
        ipv4_address: 8.8.8.5
    ports:
      - 443:443
  dnsmasq:
    image: alpine:3.6
    cap_add:
      - NET_ADMIN
    command: /bin/sh -c "apk update; apk add dnsmasq; dnsmasq --no-daemon --log-queries --address=/amazonaws.com/8.8.8.5"
    container_name: dnsmasq
    expose:
      - 53
    networks:
      files_network:
        ipv4_address: 8.8.8.8 # Replace Google's nameserver 8.8.8.8
  files:
    build: .
    container_name: files
    depends_on:
      - localstack
      - dnsmasq
    environment:
      - FILES_AWS_ACCESS_KEY_ID=key
      - FILES_AWS_SECRET_ACCESS_KEY=secret
      - FILES_AWS_REGION=us-east-1
      - FILES_AWS_S3_BUCKET=files-test
      - FILES_PORT=9999
      - FILES_URL_HOST=localhost
      - FILES_URL_PORT=8080
    networks:
      - files_network
    ports:
      - 8080:9999

# Files is configured to use Google's nameserver 8.8.8.8 as DNS resolver.
# To avoid requests to AWS S3 on development and test environments, Google's nameserver
# is replaced with a Dnsmasq server, re-assigning the IP address 8.8.8.8.
networks:
  files_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 8.8.8.0/24
